DJANGO/cbv/cbv/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cbv_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^cbv_app/', include('cbv_app.urls', namespace="cbv_app")),
]

DJANGO/cbv/cbv_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'cbv_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name="create"),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),

]

DJANGO/cbv/cbv_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse


class School(models.Model):
    name = models.CharField(max_length=128)
    principal = models.CharField(max_length=128)
    location = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cbv_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=128)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students')

    def __str__(self):
        return self.name

DJANGO/cbv/cbv_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.views.generic import (View,
                                  TemplateView,
                                  ListView, DetailView,
                                  CreateView,UpdateView,DeleteView)
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['inject_me'] = 'Injected content'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'cbv_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("cbv_app:list")

DJANGO/cbv/cbv_app/templates/cbv_app/cbv_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a></li>
          <li><a class="navbar-link"  href="{% url 'admin:index' %}">Admin</a></li>

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

DJANGO/cbv/cbv_app/templates/cbv_app/school_confirm_delete.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" name="btn btn-danger" value="Delete">
  <a href="{% url 'cbv_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

DJANGO/cbv/cbv_app/templates/cbv_app/school_detail.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block %}

<div class="jumbotron">

  <h1>School Detail</h1>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.name}}</p>
  <h3>Students:</h3>

  {% for student in school_detail.students.all %}
    <p>{{ student.name }} who is {{student.age}} years old.</p>
  {% endfor %}

</div>
<div class="container">
<p><a class="btn btn-warning" href='{% url "cbv_app:update" pk=school_detail.pk%}'>Update</a></p>
</div>

{% endblock %}

DJANGO/cbv/cbv_app/templates/cbv_app/school_form.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block %}

<h1>
  {% if not for.instance.pk %}
    Create School
  {% else %}
    Update School
  {% endif %}
</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="btn btn-primary" value="Submit">
  </form>

{% endblock %}

DJANGO/cbv/cbv_app/templates/cbv_app/school_list.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block %}

<h1>List of schools</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

DJANGO/cbv/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a></li>
          <li><a class="navbar-link"  href="{% url 'admin:index' %}">Admin</a></li>

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

DJANGO/cbv/templates/index.html
{% extends "base.html" %}
{% block body_block%}
<div class="jumbotron">
  <h1>Homepage</h1>

</div>
{% endblock %}